[package]
name = "day24"
version = "0.1.0"
authors = ["Nicolas Deslandes <ndeslandes@live.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.0"
generic-matrix = "0.1.0"
array2d = "0.2.1"